# window.yml

# 工作流程的名字
name: Test, Build and Release apk

# 工作流程触发的时机，这里是当一个版本标签推送到仓库时触发
on:
  push:
    tags:
      - v*

# 这个工作流程需要执行的任务
jobs:
  build:
    runs-on: windows-latest
    steps:
      # 拉取项目代码
      - uses: actions/checkout@v2
      # 建立 Flutter 环境
      - name: Flutter action
        uses: subosito/flutter-action@v1.1.1
        with:
          channel: "stable"
          flutter-version: "2.10.x"
      - run: flutter pub get
      - run: flutter build windows